pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Artifact') {
            steps {
                // Execute the shell script to build the artifact
                sh './build_artifact.sh'
            }
        }
    }

    post {
        always {
            // Cleanup can be added here if needed
        }
    }
}
